version: 2
jobs:
  build:
    runs-on: ubuntu-latest
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:15.0.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-
      - run: chmod +x gradlew

      - run: ./gradlew build -x test

#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}

  unit-tests:
    runs-on: ubuntu-latest
    docker:
      - image: cimg/openjdk:15.0.1

      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: arsen
          POSTGRES_DB: st
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo

    steps:
      - checkout

      - run: ./gradlew test --tests *.unit.*

#  e2e-tests:
#    runs-on: ubuntu-latest
#    docker:
#      - image: cimg/openjdk:15.0.1
#
#      - image: circleci/postgres:9.4
#        environment:
#          POSTGRES_USER: arsen
#          POSTGRES_DB: st
#          POSTGRES_HOST_AUTH_METHOD: trust
#
#    working_directory: ~/repo
#
#    steps:
#      - checkout
#
#      - name: Start application
#        run: ./gradlew bootRun
#
#      - name: Run e2e tests
#        run: ./gradlew test --tests *.e2e.*
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - unit-tests